# Base config
title = "Indie Academy"
languageCode = "en-us"
defaultContentLanguage = "en"
baseurl = "https://indie.academy"
theme = "hugo-indie-theme"
copyright = "&copy; 2017 Indie Academy"
googleAnalytics = "UA-91886706-1"
disqusShortname = ""
enableEmoji = true
sharing = true

[taxonomies]
	category = "categories"
	tag = "tags"

[params]
	description = "Awesome Indie Academy Template"
	author = "Onur Akpolat"
	email = "hej@indie.academy"
	newsletter = true
	mailchimp = "//academy.us15.list-manage.com/subscribe/post?u=e13eb956f39adfc0167aba5e0&amp;id=aac458223f"
	newsletterCTA = "Join our community to get the latest content to your inbox."
	particles = false

# Social accounts
[[params.social]]
	name = "facebook"
	icon = "/svg/facebook.svg"
	url = "//facebook.com/indieacademycrew"

[[params.social]]
	name = "twitter"
	icon = "/svg/twitter.svg"
 	url = "//twitter.com/theindieacademy"

[[params.social]]
	name = "github"
	icon = "/svg/github.svg"
	url = "//github.com/indieacademy"

[[params.social]]
	name = "youtube"
	icon = "/svg/youtube.svg"
	url = "//youtube.com"

# Legal footer links
[[params.legal]]
	name = "Privacy Policy"
 	url = "/privacy"

[[params.legal]]
	name = "Imprint"
	url = "/imprint"

[[params.legal]]
	name = "Contact us"
	url = "/contact"

# Navigation menu
[[menu.main]]
	name = "Projects"
	url = "/"
	identifier = "projects"
	weight = 1

[[menu.main]]
	name = "Blog"
	url = "#"
	identifier = "blog"
	weight = 2

[[menu.main]]
	name = "Philosophy"
	url = "#"
	identifier = "philosophy"
	weight = 3

[[menu.main]]
	name = "FAQ"
	url = "#"
	identifier = "faq"
	weight = 4

[[menu.main]]
	name = "Subscribe"
	url = "#modalNewsletter"
	identifier = "subscribebtn"
	weight = 5

# Configure the English version of the website
[languages.en]
	languageCode = "en-us"